//  This file is automatically generated. DO NOT EDIT, all your changes would be lost.
//  https://pub.dartlang.org/packages/iconfont_convert

import 'package:flutter/material.dart';

class IconFont {
  static const String _family = 'iconfont';
  
  IconFont._();
  
  static const IconData trends = IconData(0xe601, fontFamily: _family); // 动态
  static const IconData playlist = IconData(0xe6d2, fontFamily: _family); // playlist
  static const IconData danmukai = IconData(0xe8dc, fontFamily: _family); // 弹幕开
  static const IconData danmuguanbi = IconData(0xe600, fontFamily: _family); // 弹幕关闭-copy
  static const IconData share = IconData(0xe63e, fontFamily: _family); // share
  static const IconData coin = IconData(0xe615, fontFamily: _family); // coin
}

class _PreviewIcon {
  const _PreviewIcon(this.icon, this.name, this.propName);

  final IconData icon;
  final String name;
  final String propName;
}

class IconFontPreview extends StatelessWidget {
  const IconFontPreview({Key? key}) : super(key: key);

  static const iconList = <_PreviewIcon>[
    _PreviewIcon(IconFont.trends, "trends", "动态"),
    _PreviewIcon(IconFont.playlist, "playlist", "playlist"),
    _PreviewIcon(IconFont.danmukai, "danmukai", "弹幕开"),
    _PreviewIcon(IconFont.danmuguanbi, "danmuguanbi", "弹幕关闭-copy"),
    _PreviewIcon(IconFont.share, "share", "share"),
    _PreviewIcon(IconFont.coin, "coin", "coin"),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('IconFont'),
      ),
      body: GridView.count(
        shrinkWrap: true,
        crossAxisCount: 4,
        children: iconList.map((e) {
          return InkWell(
            onTap: () {
              //
            },
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Container(
                  margin: const EdgeInsets.only(bottom: 8),
                  child: Icon(e.icon),
                ),
                Text(e.name, style: const TextStyle(fontSize: 12), overflow: TextOverflow.ellipsis, maxLines: 1),
                Text(e.propName, style: const TextStyle(fontSize: 12), overflow: TextOverflow.ellipsis, maxLines: 1),
              ],
            ),
          );
        }).toList(),
      ),
    );
  }
}
